import React, { useState } from "react";
import { auth, db } from "../../../firebase.config";
import { doc, updateDoc, deleteField } from "firebase/firestore";
import { 
  sendPasswordResetEmail,
  updatePassword, 
  EmailAuthProvider, 
  reauthenticateWithCredential 
} from "firebase/auth";
import { Lock, CheckCircle, AlertCircle, Eye, EyeOff, Mail } from "lucide-react";
import { toast } from "react-toastify";

/**
 * PasswordChoiceModal - First-time login for admin-created accounts
 * - Keep Password: Continue with current password
 * - Change Password: Send Firebase password reset email
 * - Cannot close until choice is made
 */

export default function PasswordChoiceModal({ 
  currentPassword, 
  userEmail,
  firstName,
  onComplete 
}) {
  const [choice, setChoice] = useState(null); // "keep" or "change"
  const [loading, setLoading] = useState(false);

  // Handle Keep Password
  const handleKeepPassword = async () => {
    setLoading(true);
    try {
      const user = auth.currentUser;
      if (!user) throw new Error("No user logged in");

      // Update Firestore - Remove autoGeneratedPassword for security
      await updateDoc(doc(db, "users", user.uid), {
        passwordChoiceMade: true,
        passwordChoice: "kept",
        passwordChoiceDate: new Date().toISOString(),
        autoGeneratedPassword: deleteField(),
        updatedAt: new Date().toISOString(),
      });

      toast.success("Password confirmed successfully!");
      
      if (onComplete) onComplete();
    } catch (err) {
      console.error("Keep password error:", err);
      toast.error("Failed to save choice: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Handle Change Password - Send Firebase Reset Email
  const handleChangePassword = async () => {
    setLoading(true);
    try {
      const user = auth.currentUser;
      if (!user) throw new Error("No user logged in");

      // Send Firebase password reset email
      await sendPasswordResetEmail(auth, userEmail);

      // Update Firestore
      await updateDoc(doc(db, "users", user.uid), {
        passwordChoiceMade: true,
        passwordChoice: "changed",
        passwordChoiceDate: new Date().toISOString(),
        autoGeneratedPassword: deleteField(),
        updatedAt: new Date().toISOString(),
      });

      toast.success(
        "Password reset email sent! Check your inbox and follow the link to set your new password.",
        { autoClose: 7000 }
      );
      
      // Sign out user so they can use the reset link
      setTimeout(async () => {
        try {
          await auth.signOut();
        } catch (e) {
          console.error("Sign out error:", e);
        }
      }, 3000);

    } catch (err) {
      console.error("Change password error:", err);
      
      if (err.code === "auth/too-many-requests") {
        toast.error("Too many requests. Please try again later.");
      } else if (err.code === "auth/user-not-found") {
        toast.error("User not found. Please contact administrator.");
      } else {
        toast.error("Failed to send reset email: " + err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full overflow-hidden animate-in fade-in zoom-in duration-300">
        {/* Header */}
        <div className="bg-gradient-to-r from-cyan-600 to-blue-600 px-6 py-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
              <Lock className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white">Welcome, {firstName}!</h2>
              <p className="text-cyan-50 text-sm mt-1">First-time login - Password setup required</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-6">
          {/* Information Box */}
          <div className="bg-blue-50 border-l-4 border-blue-500 rounded-lg p-4 mb-6">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
              <div className="text-sm text-blue-800">
                <p className="font-semibold mb-1">Your account was created by an administrator</p>
                <p>An auto-generated password has been assigned. You can either:</p>
                <ul className="list-disc list-inside mt-2 space-y-1 ml-2">
                  <li><strong>Keep</strong> the current password</li>
                  <li><strong>Change</strong> your password (reset email will be sent)</li>
                </ul>
                <p className="mt-2 font-medium">⚠️ You must make a choice to continue.</p>
              </div>
            </div>
          </div>

          {/* Choice Selection */}
          {!choice ? (
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-gray-800 mb-4">Choose an option:</h3>
              
              {/* Keep Password Option */}
              <button
                onClick={() => setChoice("keep")}
                disabled={loading}
                className="w-full p-6 border-2 border-gray-200 rounded-xl hover:border-cyan-500 hover:bg-cyan-50 transition-all group text-left disabled:opacity-50"
              >
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center group-hover:bg-green-200 transition-colors">
                    <CheckCircle className="w-6 h-6 text-green-600" />
                  </div>
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold text-gray-800 mb-1">Keep Current Password</h4>
                    <p className="text-sm text-gray-600">
                      Continue using the auto-generated password provided by your administrator.
                    </p>
                    <div className="mt-2 text-xs text-gray-500 bg-gray-50 rounded px-3 py-2 inline-block">
                      ✓ Quick and easy - Start using the system immediately
                    </div>
                  </div>
                </div>
              </button>

              {/* Change Password Option */}
              <button
                onClick={() => setChoice("change")}
                disabled={loading}
                className="w-full p-6 border-2 border-gray-200 rounded-xl hover:border-cyan-500 hover:bg-cyan-50 transition-all group text-left disabled:opacity-50"
              >
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center group-hover:bg-blue-200 transition-colors">
                    <Mail className="w-6 h-6 text-blue-600" />
                  </div>
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold text-gray-800 mb-1">Change Password</h4>
                    <p className="text-sm text-gray-600">
                      Send a password reset email to <strong>{userEmail}</strong> to create your own password.
                    </p>
                    <div className="mt-2 text-xs text-gray-500 bg-gray-50 rounded px-3 py-2 inline-block">
                      ✓ More secure - Create a memorable password
                    </div>
                  </div>
                </div>
              </button>
            </div>
          ) : choice === "keep" ? (
            /* Keep Password Confirmation */
            <div className="space-y-4">
              <button
                onClick={() => setChoice(null)}
                className="text-sm text-cyan-600 hover:text-cyan-700 font-medium mb-4"
              >
                ← Back to options
              </button>

              <div className="bg-green-50 border border-green-200 rounded-lg p-6">
                <div className="flex items-start gap-3 mb-4">
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-gray-800 mb-2">Confirm: Keep Current Password</h4>
                    <p className="text-sm text-gray-600 mb-3">
                      By clicking "Confirm", you'll continue using your current auto-generated password.
                    </p>
                    <div className="bg-white rounded-lg p-3 border border-green-200 mb-3">
                      <p className="text-xs text-gray-500 mb-1">Your current password:</p>
                      <p className="font-mono text-sm font-semibold text-gray-800">{currentPassword}</p>
                    </div>
                    <p className="text-xs text-gray-500">
                      💡 Save this password in a secure location. You can change it later from your profile settings.
                    </p>
                  </div>
                </div>

                <div className="flex gap-3 mt-4">
                  <button
                    onClick={() => setChoice(null)}
                    disabled={loading}
                    className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 font-medium disabled:opacity-50"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleKeepPassword}
                    disabled={loading}
                    className="flex-1 px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    {loading ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="w-4 h-4" />
                        Confirm & Continue
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          ) : (
            /* Change Password - Send Reset Email */
            <div className="space-y-4">
              <button
                onClick={() => setChoice(null)}
                className="text-sm text-cyan-600 hover:text-cyan-700 font-medium mb-4"
              >
                ← Back to options
              </button>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                <div className="flex items-start gap-3 mb-4">
                  <Mail className="w-6 h-6 text-blue-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-gray-800 mb-2">Send Password Reset Email</h4>
                    <p className="text-sm text-gray-600 mb-3">
                      A password reset email will be sent to:
                    </p>
                    <div className="bg-white rounded-lg p-3 border border-blue-200 mb-3">
                      <p className="font-semibold text-gray-800">{userEmail}</p>
                    </div>
                    
                    <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-3">
                      <p className="text-xs text-amber-800">
                        <strong>📧 What happens next:</strong>
                      </p>
                      <ol className="text-xs text-amber-800 mt-2 ml-4 space-y-1 list-decimal">
                        <li>Password reset email will be sent to your inbox</li>
                        <li>You'll be automatically logged out</li>
                        <li>Check your email and click the reset link</li>
                        <li>Create your new password</li>
                        <li>Log in with your new password</li>
                      </ol>
                    </div>

                    <p className="text-xs text-gray-500">
                      💡 Make sure to check your spam folder if you don't see the email within a few minutes.
                    </p>
                  </div>
                </div>

                <div className="flex gap-3 mt-4">
                  <button
                    onClick={() => setChoice(null)}
                    disabled={loading}
                    className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 font-medium disabled:opacity-50"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleChangePassword}
                    disabled={loading}
                    className="flex-1 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    {loading ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Sending Email...
                      </>
                    ) : (
                      <>
                        <Mail className="w-4 h-4" />
                        Send Reset Email
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer Note */}
        <div className="bg-gray-50 px-6 py-4 border-t">
          <p className="text-xs text-gray-600 text-center">
            🔒 This is a one-time setup. You can change your password anytime from your profile settings.
          </p>
        </div>
      </div>
    </div>
  );
}