import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { auth } from "../../firebase.config";
import { sendPasswordResetEmail, signInWithEmailAndPassword } from "firebase/auth";
import { doc, getDoc, updateDoc } from "firebase/firestore";
import { db } from "../../firebase.config";
import PatientSidebar from "./patientComponent/patientSidebar";
import PatientAppointment from "./patientPages/patientAppointment";
import PatientBilling from "./patientPages/patientBilling";
import PatientProfile from "./patientPages/patientProfile";
import PatientDashboard from "./patientPages/patientDashboard";
import PatientNotication from "./patientPages/patientNotification";
import PatientTimeline from "./patientPages/patientTimeline";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Password Re-authentication Modal (after reset)
function PasswordReauthModal({ userEmail, onSuccess, onBack, autoGeneratedPassword }) {
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!password.trim()) {
      toast.error("Please enter your new password");
      return;
    }

    setLoading(true);
    
    try {
      // First, fetch the latest user data to get autoGeneratedPassword
      const userRef = doc(db, "users", auth.currentUser.uid);
      const userDoc = await getDoc(userRef);
      
      if (userDoc.exists()) {
        const userData = userDoc.data();
        const storedAutoPassword = userData.autoGeneratedPassword;
        
        // CRITICAL: Check if user is trying to use the auto-generated password
        if (storedAutoPassword && password.trim() === storedAutoPassword.trim()) {
          toast.error("⚠️ No changes detected! You're still using the auto-generated password. Please reset your password via the email link first, or go back and select 'Keep Password'.");
          setPassword("");
          setLoading(false);
          return;
        }
      }

      // Try to sign in with new password
      await signInWithEmailAndPassword(auth, userEmail, password);
      
      // If we reach here, login succeeded with a DIFFERENT password
      toast.success("Password verified! Welcome back.");
      onSuccess();
    } catch (error) {
      console.error("Re-authentication error:", error);
      
      if (error.code === "auth/wrong-password" || error.code === "auth/invalid-credential") {
        toast.error("Incorrect password. Please make sure you've reset your password via the email link.");
      } else if (error.code === "auth/too-many-requests") {
        toast.error("Too many failed attempts. Please try again later.");
      } else {
        toast.error("Failed to verify password. Please try again.");
      }
      setPassword("");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-gray-300 rounded-lg shadow-2xl p-8 max-w-md w-full">
        {/* Back Button */}
        <button
          onClick={onBack}
          className="mb-4 flex items-center text-gray-600 hover:text-gray-800 transition"
        >
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          <span className="font-medium">Back to Options</span>
        </button>

        <div className="text-center mb-6">
          <div className="mx-auto w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
            <svg
              className="w-8 h-8 text-green-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
              />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-gray-800 mb-2">
            Check Your Email
          </h2>
          <p className="text-gray-600 mb-3">
            We've sent a password reset link to:
          </p>
          <p className="text-base font-semibold text-gray-800 mb-4">
            {userEmail}
          </p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
            <p className="text-sm text-blue-800">
              <strong>💡 Tip:</strong> Check your <strong>Spam/Junk</strong> folder if you don't see it in your inbox.
            </p>
          </div>
        </div>

        <div className="border-t border-gray-200 pt-6">
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Enter Your New Password
              </label>
              <div className="relative">
                <input
                  type={showPassword ? "text" : "password"}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Enter new password after resetting"
                  disabled={loading}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100 pr-12"
                  autoFocus
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700"
                  tabIndex={-1}
                >
                  {showPassword ? (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7-1.274 4.057-5.064 7-9.543 7-4.478 0-8.268-2.943-9.543-7a10.025 10.025 0 014.134-5.411z" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                  )}
                </button>
              </div>
              <p className="text-xs text-gray-500 mt-2">
                After resetting via email, enter your new password here
              </p>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white font-semibold py-3 px-6 rounded-lg transition duration-200 flex items-center justify-center"
            >
              {loading ? (
                <>
                  <svg
                    className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  Verifying...
                </>
              ) : (
                <>
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
                  </svg>
                  Login with New Password
                </>
              )}
            </button>
          </form>

          <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-xs text-amber-800">
              <strong>⚠️ Note:</strong> You cannot use your old auto-generated password. If you haven't changed it yet, please go back and select "Keep Password" instead.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// Password Choice Modal Component
function PasswordChoiceModal({ userEmail, onChoiceMade, onResetPassword }) {
  const [loading, setLoading] = useState(false);

  const handleKeepPassword = async () => {
    setLoading(true);
    try {
      const userId = auth.currentUser.uid;
      const userRef = doc(db, "users", userId);
      
      await updateDoc(userRef, {
        passwordChoiceMade: true,
        passwordChoice: "keep",
        passwordChoiceDate: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });

      toast.success("Password kept successfully!");
      onChoiceMade();
    } catch (error) {
      console.error("Error updating password choice:", error);
      toast.error("Failed to save choice. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleResetPassword = async () => {
    setLoading(true);
    try {
      // Send password reset email
      await sendPasswordResetEmail(auth, userEmail);
      
      // Update Firestore with reset choice but NOT passwordChoiceMade yet
      const userId = auth.currentUser.uid;
      const userRef = doc(db, "users", userId);
      
      await updateDoc(userRef, {
        passwordChoice: "reset",
        passwordResetRequested: true,
        passwordResetDate: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });

      toast.success("Password reset email sent! Check your inbox.");
      
      // Transform modal to password input (no logout, no redirect)
      onResetPassword();
    } catch (error) {
      console.error("Error sending reset email:", error);
      toast.error("Failed to send reset email. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-2xl p-8 max-w-md w-full">
        <div className="text-center mb-6">
          <div className="mx-auto w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-4">
            <svg
              className="w-8 h-8 text-blue-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-gray-800 mb-2">
            Welcome to Your Account
          </h2>
          <p className="text-gray-600">
            Please choose what to do with your password
          </p>
        </div>

        <div className="space-y-4">
          <button
            onClick={handleKeepPassword}
            disabled={loading}
            className="w-full bg-green-600 hover:bg-green-700 disabled:bg-green-300 text-white font-semibold py-4 px-6 rounded-lg transition duration-200 flex items-center justify-center"
          >
            {loading ? (
              <span className="flex items-center">
                <svg
                  className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                Processing...
              </span>
            ) : (
              <>
                <svg
                  className="w-5 h-5 mr-2"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
                Keep Current Password
              </>
            )}
          </button>

          <button
            onClick={handleResetPassword}
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white font-semibold py-4 px-6 rounded-lg transition duration-200 flex items-center justify-center"
          >
            {loading ? (
              <span className="flex items-center">
                <svg
                  className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                Sending Email...
              </span>
            ) : (
              <>
                <svg
                  className="w-5 h-5 mr-2"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                  />
                </svg>
                Reset Password via Email
              </>
            )}
          </button>
        </div>

        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <p className="text-sm text-gray-600 text-center">
            <strong>Note:</strong> If you choose to reset, a password reset link
            will be sent to <strong>{userEmail}</strong>
          </p>
        </div>
      </div>
    </div>
  );
}

export default function PatientApp() {
  const navigate = useNavigate();

  // page state (must match keys emitted by patientSidebar)
  const [page, setPage] = useState("Patient Dashboard");

  // sidebar states
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  // notification sync states
  const [notificationTrigger, setNotificationTrigger] = useState(0);
  const [selectedNotificationId, setSelectedNotificationId] = useState(null);

  // Password choice modal states
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [showReauthModal, setShowReauthModal] = useState(false);
  const [userEmail, setUserEmail] = useState("");
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState(null);
  const [checkingPasswordChoice, setCheckingPasswordChoice] = useState(true);

  // Check screen size
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth < 768);
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // role + auth guard
  useEffect(() => {
    const role = localStorage.getItem("role");
    if (role !== "patient") {
      localStorage.clear();
      navigate("/", { replace: true });
      return;
    }

    const unsub = auth.onAuthStateChanged((user) => {
      if (!user) {
        localStorage.removeItem("role");
        navigate("/", { replace: true });
      }
    });

    return () => {
      if (typeof unsub === "function") unsub();
    };
    // eslint-disable-next-line
  }, [navigate]);

  // Check if user needs to make password choice OR needs to re-authenticate after reset
  useEffect(() => {
    const checkPasswordChoice = async () => {
      try {
        const user = auth.currentUser;
        if (!user) {
          setCheckingPasswordChoice(false);
          return;
        }

        setUserEmail(user.email);

        const userRef = doc(db, "users", user.uid);
        const userDoc = await getDoc(userRef);

        if (userDoc.exists()) {
          const userData = userDoc.data();
          const hasChoiceMade = userData.passwordChoiceMade === true;
          const hasResetRequested = userData.passwordResetRequested === true;
          const createdByPatient = userData.createdByPatient === true;
          
          // Store auto-generated password if it exists
          if (userData.autoGeneratedPassword) {
            setAutoGeneratedPassword(userData.autoGeneratedPassword);
          }
          
          // If account was created by patient themselves (self-registration), skip modal entirely
          if (createdByPatient) {
            setShowPasswordModal(false);
            setShowReauthModal(false);
            setCheckingPasswordChoice(false);
            return;
          }
          
          // If reset was requested but not completed yet, show re-auth modal
          if (hasResetRequested && !hasChoiceMade) {
            setShowReauthModal(true);
            setShowPasswordModal(false);
          } 
          // If no choice made yet (admin-created account), show password choice modal
          else if (!hasChoiceMade) {
            setShowPasswordModal(true);
            setShowReauthModal(false);
          }
          // If choice already made, proceed to system
          else {
            setShowPasswordModal(false);
            setShowReauthModal(false);
          }
        } else {
          setShowPasswordModal(false);
          setShowReauthModal(false);
        }
      } catch (error) {
        console.error("Error checking password choice:", error);
        setShowPasswordModal(false);
        setShowReauthModal(false);
      } finally {
        setCheckingPasswordChoice(false);
      }
    };

    const unsubscribe = auth.onAuthStateChanged((user) => {
      if (user) {
        checkPasswordChoice();
      } else {
        setCheckingPasswordChoice(false);
      }
    });

    return () => unsubscribe();
  }, []);

  // handle logout
  const handleLogout = async () => {
    try {
      if (auth && typeof auth.signOut === "function") {
        await auth.signOut();
      } else {
        const { signOut } = await import("firebase/auth");
        await signOut(auth);
      }
    } catch (err) {
      console.error("Sign out error:", err);
    } finally {
      try {
        localStorage.removeItem("role");
      } catch (e) {}
      navigate("/", { replace: true });
    }
  };

  // Handle navigation to notifications page
  const handleNavigateToNotifications = (notificationId = null) => {
    setSelectedNotificationId(notificationId);
    setPage("Patient Notifications");
  };

  // Handle back from notifications
  const handleBackFromNotifications = () => {
    setSelectedNotificationId(null);
    setPage("Patient Dashboard");
    setNotificationTrigger(prev => prev + 1);
  };

  // Handle password choice made (Keep Password)
  const handlePasswordChoiceMade = () => {
    setShowPasswordModal(false);
  };

  // Handle reset password chosen
  const handleResetPasswordChosen = () => {
    setShowPasswordModal(false);
    setShowReauthModal(true);
    // Stay on same page, just transform the modal
  };

  // Handle back from re-auth modal to password choice modal
  const handleBackToOptions = () => {
    setShowReauthModal(false);
    setShowPasswordModal(true);
  };

  // Handle successful re-authentication after reset
  const handleReauthSuccess = async () => {
    try {
      const userId = auth.currentUser.uid;
      const userRef = doc(db, "users", userId);
      
      // Mark password choice as completed and remove autoGeneratedPassword
      const updateData = {
        passwordChoiceMade: true,
        passwordResetRequested: false,
        passwordResetCompleted: true,
        passwordResetCompletedDate: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      
      // Remove autoGeneratedPassword field if it exists
      if (autoGeneratedPassword) {
        updateData.autoGeneratedPassword = null;
      }

      await updateDoc(userRef, updateData);

      setShowReauthModal(false);
      toast.success("Welcome! You can now access the system.");
    } catch (error) {
      console.error("Error completing password reset:", error);
      toast.error("Failed to complete setup. Please try again.");
    }
  };

  // Handle cancel re-auth (logout) - REMOVED, not needed anymore
  const handleReauthCancel = async () => {
    await handleLogout();
  };

  // render pages
  const renderPage = () => {
    switch (page) {
      case "Patient Dashboard":
        return <PatientDashboard />;
      case "Patient Appointment":
        return <PatientAppointment />;
      case "Patient Billing":
        return <PatientBilling />;
      case "Patient Timeline":
        return <PatientTimeline />;
      case "Patient Notifications":
        return (
          <PatientNotication
            initialNotificationId={selectedNotificationId}
            onBack={handleBackFromNotifications}
          />
        );
      case "Patient Profile":
        return <PatientProfile />;
      default:
        return <PatientDashboard />;
    }
  };

  // Show loading while checking password choice
  if (checkingPasswordChoice) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  // Show password re-authentication modal (after reset email sent)
  if (showReauthModal) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <PasswordReauthModal
          userEmail={userEmail}
          onSuccess={handleReauthSuccess}
          onBack={handleBackToOptions}
          autoGeneratedPassword={autoGeneratedPassword}
        />
        <ToastContainer
          position="top-right"
          autoClose={3500}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnHover
        />
      </div>
    );
  }

  // Show password choice modal (first time)
  if (showPasswordModal) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <PasswordChoiceModal
          userEmail={userEmail}
          onChoiceMade={handlePasswordChoiceMade}
          onResetPassword={handleResetPasswordChosen}
        />
        <ToastContainer
          position="top-right"
          autoClose={3500}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnHover
        />
      </div>
    );
  }

  // Only render the full system if password choice has been made
  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Mobile Menu Button */}
      {isMobile && (
        <button
          onClick={() => setSidebarOpen(true)}
          className="fixed top-4 left-4 z-40 p-2 bg-white rounded-lg shadow-lg md:hidden"
        >
          <svg
            className="w-6 h-6 text-gray-700"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      )}

      {/* Sidebar */}
      <PatientSidebar
        setPage={(k) => {
          setPage(k);
          if (isMobile) {
            setSidebarOpen(false);
          }
          if (k !== "Patient Notifications") {
            setSelectedNotificationId(null);
          }
        }}
        currentPage={page}
        handleLogout={handleLogout}
        collapsed={sidebarCollapsed}
        onToggle={(next) => setSidebarCollapsed(typeof next === "boolean" ? next : !sidebarCollapsed)}
        mobileOpen={sidebarOpen}
        onMobileClose={() => setSidebarOpen(false)}
      />

      {/* Main area */}
      <div className="flex-1 flex flex-col min-h-screen">
        <main className="flex-1 overflow-auto">
          {renderPage()}
        </main>
      </div>

      {/* Toast container */}
      <ToastContainer
        position="top-right"
        autoClose={3500}
        hideProgressBar={false}
        newestOnTop
        closeOnClick
        pauseOnHover
      />
    </div>
  );
}